### ISSUE TITLE
Add support for different virtual image files

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#10]
Add support for all of these formats: https://en.wikibooks.org/wiki/QEMU/Images#Image_types

**Comment by main--** [comment]
I don't think this is a reasonable goal. Sure, supporting raw is a no-brainer and so is qcow2 but does anything beyond that make sense? AFAICS you would only use any of these formats if you're stuck with legacy images and can't convert them for whatever reason. This is not what we're facing here: We actually create the image file so why would we use anything that isn't qcow2?

**Comment by oberien** [comment]
Actually that's a good point. And thinking about it we don't even need qcow2. If someone switches from Windows because of our tool, he'd have a raw windows image anyways (which he'd need to tweak with proper drivers). If someone uses Windows in a VM and wants to switch over to windows-gaming, he'll just convert that file format into raw.
