### ISSUE TITLE
If fetching clipboard times out, entry is super slow

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#133]
Fetching the clipboard is done synchronously with a timeout of a few seconds. If no clipboard can be fetched, we have to wait for the timeout before we can enter.

**Comment by main--** [comment]
IMO #119 would be a sufficient workaround for now.

A proper long-term implementation of #23 would not have this issue anyways as we can make the Windows Clipboard API [fall back](https://msdn.microsoft.com/en-us/library/windows/desktop/ms649014(v=vs.85).aspx#_win32_Delayed_Rendering) to something Linux-like and have them interoperate:

* On startup: Assert clipboard ownership on Windows (delayed rendering)
* When we lose clipboard ownership on Windows (we should get a window message about that): Assert clipboard ownership on Linux
* When we lose clipboard ownership on Linux: Assert clipboard ownership on Windows (delayed rendering)
* When we receive a clipboard rendering request on Windows, we do the X11 clipboard dance (request contents, forward to VM)
* When we receive an X11 clipboard request, we grab the data from Windows (request contents from VM, forward to X11 window)

**Comment by oberien** [comment]
Fixed by #135
