### ISSUE TITLE
We are always segfaulting on exit

### ISSUE THREAD

**Issue by main--** [main--/windows-gaming#152]
This is most definitely a bug, probably in some library but still. We need to fix this.

**Comment by oberien** [comment]
<img src="http://i0.kym-cdn.com/photos/images/original/001/191/035/135.png" width=100/>
I only ever segfaulted once and usually (meaning always-1) get `ERROR: We errored: Connection reset by peer (os error 104)`.

**Comment by main--** [comment]
This seems to be resolved.
