### ISSUE TITLE
/run/windows-gaming-driver non-existent

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#17]

**Comment by main--** [comment]
Yeah but ... doesn't the code actually just create that directory? I'm pretty sure it does.

**Comment by oberien** [comment]
![](http://i1.kym-cdn.com/entries/icons/original/000/021/665/DpQ9YJl.png)

I don't even know what I wanted with this anymore. IIRC it happened when running the setup as root, but again. Therefore: Closed until someone else can add a description to this issue ;)
