### ISSUE TITLE
Make sudo work

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#19]
Accessing `/dev/vfio/1` needs sudo permissions, which the setup does not have in user-mode.

**Comment by main--** [comment]
It really shouldn't. After all, we're shipping a [udev rule](https://github.com/main--/windows-gaming/blob/f457273642f8038e6b0f72431597bd31c9d10856/misc/80-vfio.rules#L2) for that.

Are you sure this needs root or is this issue actually about the fact that the wizard should add the user to the `vfio` group?

**Comment by oberien** [comment]
I guess the latter. Close in favor of #38
