### ISSUE TITLE
Add descriptions why sudo is needed for each step it's needed

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#20]

**Comment by main--** [comment]
Dunno. It should be obvious for most, shouldn't it? Like how else do you expect us to edit your root-owned 644 `/etc/mkinitcpio.conf`? Magic?

And sure, printing `sudo` commands so you don't have to fully trust us makes sense *in theory* - but you gain nothing. Not only can we just fake the whole thing, we could also simply run our payload *after* any sudo command as we then have a session. Or, you know, abuse the fact that we can already install files and run code as root. Either we modify your system for you and you trust us to do the right thing or you do it yourself entirely - **there is no middle ground** (compare: self-xss).
