### ISSUE TITLE
Catch SIGINT just like SIGTERM while qemu is running

### ISSUE THREAD

**Issue by main--** [main--/windows-gaming#25]
And perhaps some other signals as well

**Comment by main--** [comment]
Update: While we are now catching SIGINT, it's pretty useless as a shell will always send that signal to *all* active processes on Ctrl+C, causing qemu to terminate instantly anyways.

**Comment by oberien** [comment]
SIGINT (and similar) are sent to the whole process group. With `setpgid(pid, pgid)` (and `pgid` set to 0) we can set the process group id of qemu to its own, which will mean that SIGINTs won't be sent to it on Ctrl+C.
