### ISSUE TITLE
USB Passthrough

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#27]
- [x] udev picker to select mouse and keyboard
- [ ] support headless setup
- [x] support passing through other USB devices as well
- [x] allow more granular selection and setup of USB devices to select which flags should be set (e.g. permanent, bind ById or ByPort, …)

**Comment by oberien** [comment]
AFAICS we do have a nogui setup. Or do you mean a nocli one? Also we do support passing through other USB devices even permanently with #56 and #60 .

**Comment by main--** [comment]
This is basically done. If we ever do headless setup, it will be powered by #92.
