### ISSUE TITLE
check that the entire iommu group was passed through

### ISSUE THREAD

**Issue by main--** [main--/windows-gaming#36]
make sure all bindings worked, not just any of them

**Comment by moritzuehling** [comment]
Problem scenario: Your nvidia-HD-Audiodrivers are passed through, the rest isn't. "That won't happen" you say? 

It did, apparently the nvidia-drivers try to grab the GPU asap (on ubuntu 16.10, for example), but are more lenient with the audio-device, so we get in a state where the assistent thinks that the GPU is passed through, when it really isn't.

**Comment by main--** [comment]
@moritzuehling Isn't that scenario literally why I created this issue?

**Comment by main--** [comment]
Actually, we [are](https://github.com/main--/windows-gaming/blob/b411bee8594f8525b44295b2ed104ed541137e72/windows-gaming-driver/src/setup/wizard.rs#L173) checking this already. Any idea why it didn't work in your case?

**Comment by main--** [comment]
No response, closing for now.
