### ISSUE TITLE
Setup panics if config directory is non-existent

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#6]
The config file's directory defaults to `~/.config/windows-gaming-driver/`. If `windows-gaming-driver` does not exist, the setup panics.

**Comment by main--** [comment]
I'm guessing this happens when saving the config file? Good catch, should be an easy fix then.

**Comment by oberien** [comment]
This is actually the same issue as #17 , but this is in user-space while #17 is in sudo-space.

**Comment by main--** [comment]
It can't be. This is about config file. #17 is about the runtime directory aka temp folder.

**Comment by main--** [comment]
fwiw this would be fixed by #33
