### ISSUE TITLE
Setup: auto-editing mkinitcpio does not work if mkinitcpio.conf is a link

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#7]
```
sudo: /etc/mkinitcpio.conf: editing symbolic links is not permitted
Success!
```

**Comment by main--** [comment]
Why does [this check](https://github.com/main--/windows-gaming/blob/ca75eb8b0a45ffd277c022f238ecf1fc357ee40e/windows-gaming-driver/src/setup/wizard.rs#L107) not trigger (0c4b06dc2c2a7d25369785bf905e83831b05b053 was already supposed to fix this issue)?

```rust
        // File::open works on symlinks but sudo -e does not.
        if !Path::new(MKINITCPIO_CONF).is_file() {
            return Ok(false);
        }
```

**Comment by oberien** [comment]
[From the doc of `is_file`](https://doc.rust-lang.org/std/path/struct.Path.html#method.is_file)
> This function will traverse symbolic links to query information about the destination file. In case of broken symbolic links this will return `false`.

For detection we could check if [`symlink_metadata`](https://doc.rust-lang.org/std/path/struct.Path.html#method.symlink_metadata) or [`read_link`](https://doc.rust-lang.org/std/path/struct.Path.html#method.read_link) returns `Err(_)`.
