### ISSUE TITLE
Setup: Add warning to change libgl drivers and xorg.conf

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#8]
When switching from nvidia to intel graphics, one needs to remove all nvidia packets and replace them with `mesa-libgl` (and `lib32-mesa-libgl` if using multilib). Also `/etc/X11/xorg.conf` needs to be removed / adapted to not use nvidia anymore.

**Comment by main--** [comment]
Only on X11 though. This is very tricky. The wizard currently assumes that your graphical environment (if you even have one) is not using the GPU you're selecting for passthrough. Perhaps we might add a message about this (it seemed obvious enough to me) but I'm not sure automating it is even feasible. X11 vs wayland is just one of dozens of areas where we just have no clue what to do. I don't even know off the top of my head how we would hook this under e.g. Ubuntu where the user actually has a GUI with radio buttons to select the desired GPU (and driver) for the graphical environment.

**Comment by oberien** [comment]
The fanciest thing would obviously be to automatically do all this stuff. But for the time being (probably meaning forever) I'd suggest to at least print a warning or message that the windows-gaming setup assumes that you are already using the to-go linux GPU and not the windows-GPU anymore.
This could also be checked for once the user selected his GPU. If the currently used GPU is selected, print that warning, otherwise continue silently.

**Comment by moritzuehling** [comment]
> The fanciest thing would obviously be to automatically do all this stuff.

Perhaps. On ubuntu you could simply uninstall the nvidia-* packages, and it would work, which is considerably easierl.
