### ISSUE TITLE
xbuild tool is deprecated and will be removed in future updates, use msbuild instead

### ISSUE THREAD

**Issue by oberien** [main--/windows-gaming#90]

**Comment by main--** [comment]
wontfix for the forseeable future

msbuild was newly introduced simultaneously with the xbuild deprecation in mono 5.0

however

* debian jessie (stable): [v3.2.8](https://packages.debian.org/en/jessie/mono-complete)
* debian stretch (testing): [v4.6.2](https://packages.debian.org/en/stretch/mono-complete)
* debian sid (unstable!): [v4.6.2](https://packages.debian.org/en/sid/mono-complete)

feel free to reopen this in 10 years or so
