### ISSUE TITLE
USB device selection is a disaster right now

### ISSUE THREAD

**Issue by main--** [main--/windows-gaming#93]
When re-running the wizard, it still aggressively prompts for mouse and keyboard even if you already selected them

**Comment by Ediacarium** [comment]
▶ 🔊 IT'S A DISASTAH!

> Welcome!
> 
> This wizard will help you configure a PCI passthrough setup!
> Some steps are automated, others have to be done manually. Note that answering no ('n') to those will abort the wizard.
> You can abort the wizard at any point without risking corruptions except where it specifically tells you not to.
> 
> This setup assumes that you are currently running on the GPU you want Linux to run on.
> Make sure that you remove unnecessary drivers as they might interfere.
> You may also need to configure your display server's config files accordingly (e.g. xorg.conf for Xorg).
> 
> Understood? [y/n] y
> 
> Step 1: Enable IOMMU
> It's as simple as adding 'intel_iommu=on' or 'amd_iommu=on' to your kernel command line.
> Do this now, then continue here. Don't reboot yet, there's more we need to configure.
> 
> IOMMU is already enabled. Do you want to skip this step? [y/n] y
> Step 2: Select USB Devices
> 
> You have currently selected the following usb devices: 
> 	Xenta Wireless Receiver (RC Laser Pointer) [1d57:0006]
> 	Cypress Semiconductor Corp. Keyboard/Hub [04b4:0101]
> Do you want to remove them before proceeding? [y/n] n
> [0]	None of the above
> Please select the mouse you would like to pass through [0..1] 0
> [0]	None of the above
> Please select the keyboard you would like to pass through [0..1] 0
> No mouse selected. Please select your mouse from this complete list of connected devices:
> [0]	Linux Foundation 2.0 root hub [1d6b:0002]
> [1]	ASMedia Technology Inc. ASM1074 High-Speed hub [174c:2074]
> [2]	Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) [0a12:0001]
> [3]	Linux Foundation 3.0 root hub [1d6b:0003]
> [4]	ASMedia Technology Inc. ASM1074 SuperSpeed hub [174c:3074]
> [5]	Linux Foundation 2.0 root hub [1d6b:0002]
> [6]	Intel Corp. Unknown product [8087:800a]
> [7]	Linux Foundation 2.0 root hub [1d6b:0002]
> [8]	Linux Foundation 3.0 root hub [1d6b:0003]
> [9]	Linux Foundation 2.0 root hub [1d6b:0002]
> [10]	Intel Corp. Unknown product [8087:8002]
> [11]	None of the above
> Please select the usb device you would like to pass through [0..12] 11
> No keyboard selected. Please select your keyboard from this complete list of connected devices:
> [0]	Linux Foundation 2.0 root hub [1d6b:0002]
> [1]	ASMedia Technology Inc. ASM1074 High-Speed hub [174c:2074]
> [2]	Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) [0a12:0001]
> [3]	Linux Foundation 3.0 root hub [1d6b:0003]
> [4]	ASMedia Technology Inc. ASM1074 SuperSpeed hub [174c:3074]
> [5]	Linux Foundation 2.0 root hub [1d6b:0002]
> [6]	Intel Corp. Unknown product [8087:800a]
> [7]	Linux Foundation 2.0 root hub [1d6b:0002]
> [8]	Linux Foundation 3.0 root hub [1d6b:0003]
> [9]	Linux Foundation 2.0 root hub [1d6b:0002]
> [10]	Intel Corp. Unknown product [8087:8002]
> [11]	None of the above

**Comment by oberien** [comment]
Fixed with #55

**Comment by Ediacarium** [comment]
▶ 🔊 IT'S STILL A DISASTAH!

> RUST_BACKTRACE=1 windows-gaming-driver 
> Welcome!
> This wizard will help you configure a PCI passthrough setup!
> Some steps are automated, others have to be done manually. Note that answering no ('n') to those will abort the wizard.
> You can abort the wizard at any point without risking corruptions except where it specifically tells you not to.
> 
> This setup assumes that you are currently running on the GPU you want Linux to run on.
> Make sure that you remove unnecessary drivers as they might interfere.
> You may also need to configure your display server's config files accordingly (e.g. xorg.conf for Xorg).
> 
> Understood? [y/n] y
> 
> Step 1: Enable IOMMU
> It's as simple as adding 'intel_iommu=on' or 'amd_iommu=on' to your kernel command line.
> Do this now, then continue here. Don't reboot yet, there's more we need to configure.
> 
> IOMMU is already enabled. Do you want to skip this step? [y/n] y
> Step 2: Select USB Devices
> 
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
> stack backtrace:
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: <unknown>
>   14: <unknown>
>   15: <unknown>
>   16: <unknown>
>   17: __libc_start_main
>

**Comment by oberien** [comment]
Fixed with #98

**Comment by Ediacarium** [comment]
▶ 🔊 Crash and Burn

> [2017-06-30 15:12:08,283] DEBUG: Running in user mode
> [2017-06-30 15:12:08,283] DEBUG: Using config file "/home/alex/.config/windows-gaming-driver/config"
> [2017-06-30 15:12:08,283] DEBUG: Working directory is "/run/user/1000/windows-gaming-driver/"
> Welcome!
> This wizard will help you configure a PCI passthrough setup!
> Some steps are automated, others have to be done manually. Note that answering no ('n') to those will abort the wizard.
> You can abort the wizard at any point without risking corruptions except where it specifically tells you not to.
> 
> This setup assumes that you are currently running on the GPU you want Linux to run on.
> Make sure that you remove unnecessary drivers as they might interfere.
> You may also need to configure your display server's config files accordingly (e.g. xorg.conf for Xorg).
> 
> Understood? [y/n] y
> 
> Step 1: Enable IOMMU
> It's as simple as adding 'intel_iommu=on' or 'amd_iommu=on' to your kernel command line.
> Do this now, then continue here. Don't reboot yet, there's more we need to configure.
> 
> IOMMU is already enabled. Do you want to skip this step? [y/n] y
> Step 2: Select USB Devices
> 
> [0]	Xenta Wireless Receiver (RC Laser Pointer) [1d57:0006] [Bus 3.5]
> [1]	Cypress Semiconductor Corp. Keyboard/Hub [04b4:0101] [Bus 3.6]
> [2]	None of the above
> Please select the mouse you would like to pass through [0..3] 0
> [0]	Cypress Semiconductor Corp. Keyboard/Hub [04b4:0101] [Bus 3.6]
> [1]	None of the above
> Please select the keyboard you would like to pass through [0..2] 0
> Would you like to add additional devices? [y/n] y
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
> stack backtrace:
>    0:     0x564f7af9aba3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::he3bc6a5b6656842f
>    1:     0x564f7af97584 - std::sys_common::backtrace::_print::ha88d3b0e6a21594b
>    2:     0x564f7afa3b4c - std::panicking::default_hook::{{closure}}::h4c710dbcb792ff19
>    3:     0x564f7afa3700 - std::panicking::default_hook::hb28eb06feeb8b840
>    4:     0x564f7afa3f9b - std::panicking::rust_panic_with_hook::he88eaf29aec989e2
>    5:     0x564f7afa3e24 - std::panicking::begin_panic::h735e513265dd3c3e
>    6:     0x564f7afa3da9 - std::panicking::begin_panic_fmt::h4afb704fbdca6bf8
>    7:     0x564f7afa3d37 - rust_begin_unwind
>    8:     0x564f7afeffdd - core::panicking::panic_fmt::h077415e225e0e0e9
>    9:     0x564f7afeff14 - core::panicking::panic::hea472d4236204996
>   10:     0x564f7aaa2892 - <core::option::Option<T>>::unwrap::h23c051e9da598039
>                                at /build/rust/src/rustc-1.17.0-src/src/libcore/macros.rs:21
>   11:     0x564f7ac4dec3 - windows_gaming_driver::usb_device::UsbDevice::from_udev_device::hfe2e09705a24d917
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/usb_device.rs:39
>   12:     0x564f7ac558ca - windows_gaming_driver::setup::usb::list_devices::he38d0205205f388a
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/setup/usb.rs:198
>   13:     0x564f7ac54092 - windows_gaming_driver::setup::usb::pick::h93066cef1fc5d564
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/setup/usb.rs:131
>   14:     0x564f7ac52ace - windows_gaming_driver::setup::usb::select::h2ff2990bedd5731f
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/setup/usb.rs:55
>   15:     0x564f7ac5988d - windows_gaming_driver::setup::wizard::Wizard::run::h692b4b2a059a0c20
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/setup/wizard.rs:50
>   16:     0x564f7ac5c114 - windows_gaming_driver::setup::wizard::run::hbfbc68eb9c921b15
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/setup/wizard.rs:145
>   17:     0x564f7ac732e0 - windows_gaming_driver::main::h8082d4a3e1cd1e17
>                                at /home/alex/Documents/Projekte/windows-gaming/windows-gaming-driver/src/main.rs:96
>   18:     0x564f7afa3c95 - std::panicking::try::do_call::h7842cdc5d2598e69
>   19:     0x564f7afab06a - __rust_maybe_catch_panic
>   20:     0x564f7afa4851 - std::rt::lang_start::h048f4a3009fcb57f
>   21:     0x564f7ad01c22 - main
>   22:     0x7f2a97e57439 - __libc_start_main
>   23:     0x564f7a939b59 - _start
>   24:                0x0 - <unknown>
